// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HelloBook.Models;

public partial class Address
{
    public int Id { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public int Zip_code { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}