// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HelloBook.Models;

public partial class Authors
{
    public int Id { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Nationality { get; set; }

    [JsonIgnore]
    public virtual ICollection<Books> Books { get; set; } = new List<Books>();
}