// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HelloBook.Models;

public partial class Users
{
    public int Id { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int Address_id { get; set; }

    public DateTime Created_at { get; set; }

    public virtual Address Address { get; set; }
}